export enum SessionAttribute {
  USER_DETAILS = 'USER_DETAILS',
  LOGGED_STATE = 'LOGGED_STATE',
  LOGGED_PORTAL = 'LOGGED_PORTAL',
  AUTHORITIES = 'AUTHORITIES',
  AUTHORITIES_PROXY = 'AUTHORITIES_PROXY',
  SCREEN_CALLER_STACK_DATA = 'SCREEN_CALLER_STACK_DATA'
}

