import { Component, OnInit } from '@angular/core';
import {ListData} from "../../../../components/table-data/model/list-data.interface";

@Component({
  selector: 'app-table2',
  templateUrl: './table2.component.html',
  styleUrls: ['./table2.component.css']
})
export class Table2Component implements OnInit {

  public tableData!: ListData;

  constructor() { }

  ngOnInit(): void {
    this.initListData();
  }

  private initListData = () => {
    this.tableData = {
      data: [
        {
          header1: "aaaaaaaaaaaaaaaaaaaa1",
          header2: "aaaaaaaaaaaaaaaaaaaa2",
          header3: "aaaaaaaaaaaaaaaaaaaa3",
          header4: "aaaaaaaaaaaaaaaaaaaa4",
          header5: "aaaaaaaaaaaaaaaaaaaa5",
          header6: "aaaaaaaaaaaaaaaaaaaa6",
          header7: "aaaaaaaaaaaaaaaaaaaa7",
          header8: "aaaaaaaaaaaaaaaaaaaa8",
          header9: "aaaaaaaaaaaaaaaaaaaa9",
          header10: "aaaaaaaaaaaaaaaaaaaa10",
        },
        {
          header1: "bbbbbbbbbbbbbbbbbbbb1",
          header2: "bbbbbbbbbbbbbbbbbbbb2",
          header3: "bbbbbbbbbbbbbbbbbbbb3",
          header4: "bbbbbbbbbbbbbbbbbbbb4",
          header5: "bbbbbbbbbbbbbbbbbbbb5",
          header6: "bbbbbbbbbbbbbbbbbbbb6",
          header7: "bbbbbbbbbbbbbbbbbbbb7",
          header8: "bbbbbbbbbbbbbbbbbbbb8",
          header9: "bbbbbbbbbbbbbbbbbbbb9",
          header10: "bbbbbbbbbbbbbbbbbbbb10",
        },
        {
          header1: "cccccccccccccccccccc1",
          header2: "cccccccccccccccccccc2",
          header3: "cccccccccccccccccccc3",
          header4: "cccccccccccccccccccc4",
          header5: "cccccccccccccccccccc5",
          header6: "cccccccccccccccccccc6",
          header7: "cccccccccccccccccccc7",
          header8: "cccccccccccccccccccc8",
          header9: "cccccccccccccccccccc9",
          header10: "cccccccccccccccccccc10",
        },
        {
          header1: "dddddddddddddddddddd1",
          header2: "dddddddddddddddddddd2",
          header3: "dddddddddddddddddddd3",
          header4: "dddddddddddddddddddd4",
          header5: "dddddddddddddddddddd5",
          header6: "dddddddddddddddddddd6",
          header7: "dddddddddddddddddddd7",
          header8: "dddddddddddddddddddd8",
          header9: "dddddddddddddddddddd9",
          header10: "ddddddddddddddd10",
        },
        {
          header1: "eeeeeeeeee1",
          header2: "eeeeeeeeee2",
          header3: "eeeeeeeeee3",
          header4: "eeeeeeeeee4",
          header5: "eeeeeeeeee5",
          header6: "eeeeeeeeee6",
          header7: "eeeeeeeeee7",
          header8: "eeeeeeeeee8",
          header9: "eeeeeeeeee9",
          header10: "eeeeeeeeee10",
        },
        {
          header1: "ffffffffff1",
          header2: "ffffffffff2",
          header3: "ffffffffff3",
          header4: "ffffffffff4",
          header5: "ffffffffff5",
          header6: "ffffffffff6",
          header7: "ffffffffff7",
          header8: "ffffffffff8",
          header9: "ffffffffff9",
          header10: "ffffffffff10",
        },
        {
          header1: "gggggggggg1",
          header2: "gggggggggg2",
          header3: "gggggggggg3",
          header4: "gggggggggg4",
          header5: "gggggggggg5",
          header6: "gggggggggg6",
          header7: "gggggggggg7",
          header8: "gggggggggg8",
          header9: "gggggggggg9",
          header10: "gggggggggg10",
        },
        {
          header1: "hhhhhhhhhh1",
          header2: "hhhhhhhhhh2",
          header3: "hhhhhhhhhh3",
          header4: "hhhhhhhhhh4",
          header5: "hhhhhhhhhh5",
          header6: "hhhhhhhhhh6",
          header7: "hhhhhhhhhh7",
          header8: "hhhhhhhhhh8",
          header9: "hhhhhhhhhh9",
          header10: "hhhhhhhhhh10",
        },
        {
          header1: "eeeeeeeeee1",
          header2: "eeeeeeeeee2",
          header3: "eeeeeeeeee3",
          header4: "eeeeeeeeee4",
          header5: "eeeeeeeeee5",
          header6: "eeeeeeeeee6",
          header7: "eeeeeeeeee7",
          header8: "eeeeeeeeee8",
          header9: "eeeeeeeeee9",
          header10: "eeeeeeeeee10",
        },
        {
          header1: "iiiiiiiiii1",
          header2: "iiiiiiiiii2",
          header3: "iiiiiiiiii3",
          header4: "iiiiiiiiii4",
          header5: "iiiiiiiiii5",
          header6: "iiiiiiiiii6",
          header7: "iiiiiiiiii7",
          header8: "iiiiiiiiii8",
          header9: "iiiiiiiiii9",
          header10: "iiiiiiiiii10",
        },{
          header1: "aaaaaaaaaaaaaaaaaaaa1",
          header2: "aaaaaaaaaaaaaaaaaaaa2",
          header3: "aaaaaaaaaaaaaaaaaaaa3",
          header4: "aaaaaaaaaaaaaaaaaaaa4",
          header5: "aaaaaaaaaaaaaaaaaaaa5",
          header6: "aaaaaaaaaaaaaaaaaaaa6",
          header7: "aaaaaaaaaaaaaaaaaaaa7",
          header8: "aaaaaaaaaaaaaaaaaaaa8",
          header9: "aaaaaaaaaaaaaaaaaaaa9",
          header10: "aaaaaaaaaaaaaaaaaaaa10",
        },
        {
          header1: "bbbbbbbbbbbbbbbbbbbb1",
          header2: "bbbbbbbbbbbbbbbbbbbb2",
          header3: "bbbbbbbbbbbbbbbbbbbb3",
          header4: "bbbbbbbbbbbbbbbbbbbb4",
          header5: "bbbbbbbbbbbbbbbbbbbb5",
          header6: "bbbbbbbbbbbbbbbbbbbb6",
          header7: "bbbbbbbbbbbbbbbbbbbb7",
          header8: "bbbbbbbbbbbbbbbbbbbb8",
          header9: "bbbbbbbbbbbbbbbbbbbb9",
          header10: "bbbbbbbbbbbbbbbbbbbb10",
        },
        {
          header1: "cccccccccccccccccccc1",
          header2: "cccccccccccccccccccc2",
          header3: "cccccccccccccccccccc3",
          header4: "cccccccccccccccccccc4",
          header5: "cccccccccccccccccccc5",
          header6: "cccccccccccccccccccc6",
          header7: "cccccccccccccccccccc7",
          header8: "cccccccccccccccccccc8",
          header9: "cccccccccccccccccccc9",
          header10: "cccccccccccccccccccc10",
        },
        {
          header1: "dddddddddddddddddddd1",
          header2: "dddddddddddddddddddd2",
          header3: "dddddddddddddddddddd3",
          header4: "dddddddddddddddddddd4",
          header5: "dddddddddddddddddddd5",
          header6: "dddddddddddddddddddd6",
          header7: "dddddddddddddddddddd7",
          header8: "dddddddddddddddddddd8",
          header9: "dddddddddddddddddddd9",
          header10: "ddddddddddddddd10",
        },
        {
          header1: "eeeeeeeeee1",
          header2: "eeeeeeeeee2",
          header3: "eeeeeeeeee3",
          header4: "eeeeeeeeee4",
          header5: "eeeeeeeeee5",
          header6: "eeeeeeeeee6",
          header7: "eeeeeeeeee7",
          header8: "eeeeeeeeee8",
          header9: "eeeeeeeeee9",
          header10: "eeeeeeeeee10",
        },
        {
          header1: "ffffffffff1",
          header2: "ffffffffff2",
          header3: "ffffffffff3",
          header4: "ffffffffff4",
          header5: "ffffffffff5",
          header6: "ffffffffff6",
          header7: "ffffffffff7",
          header8: "ffffffffff8",
          header9: "ffffffffff9",
          header10: "ffffffffff10",
        },
        {
          header1: "gggggggggg1",
          header2: "gggggggggg2",
          header3: "gggggggggg3",
          header4: "gggggggggg4",
          header5: "gggggggggg5",
          header6: "gggggggggg6",
          header7: "gggggggggg7",
          header8: "gggggggggg8",
          header9: "gggggggggg9",
          header10: "gggggggggg10",
        },
        {
          header1: "hhhhhhhhhh1",
          header2: "hhhhhhhhhh2",
          header3: "hhhhhhhhhh3",
          header4: "hhhhhhhhhh4",
          header5: "hhhhhhhhhh5",
          header6: "hhhhhhhhhh6",
          header7: "hhhhhhhhhh7",
          header8: "hhhhhhhhhh8",
          header9: "hhhhhhhhhh9",
          header10: "hhhhhhhhhh10",
        },
        {
          header1: "eeeeeeeeee1",
          header2: "eeeeeeeeee2",
          header3: "eeeeeeeeee3",
          header4: "eeeeeeeeee4",
          header5: "eeeeeeeeee5",
          header6: "eeeeeeeeee6",
          header7: "eeeeeeeeee7",
          header8: "eeeeeeeeee8",
          header9: "eeeeeeeeee9",
          header10: "eeeeeeeeee10",
        },
        {
          header1: "iiiiiiiiii1",
          header2: "iiiiiiiiii2",
          header3: "iiiiiiiiii3",
          header4: "iiiiiiiiii4",
          header5: "iiiiiiiiii5",
          header6: "iiiiiiiiii6",
          header7: "iiiiiiiiii7",
          header8: "iiiiiiiiii8",
          header9: "iiiiiiiiii9",
          header10: "iiiiiiiiii10",
        },
        {
          header1: "aaaaaaaaaaaaaaaaaaaa1",
          header2: "aaaaaaaaaaaaaaaaaaaa2",
          header3: "aaaaaaaaaaaaaaaaaaaa3",
          header4: "aaaaaaaaaaaaaaaaaaaa4",
          header5: "aaaaaaaaaaaaaaaaaaaa5",
          header6: "aaaaaaaaaaaaaaaaaaaa6",
          header7: "aaaaaaaaaaaaaaaaaaaa7",
          header8: "aaaaaaaaaaaaaaaaaaaa8",
          header9: "aaaaaaaaaaaaaaaaaaaa9",
          header10: "aaaaaaaaaaaaaaaaaaaa10",
        },
        {
          header1: "bbbbbbbbbbbbbbbbbbbb1",
          header2: "bbbbbbbbbbbbbbbbbbbb2",
          header3: "bbbbbbbbbbbbbbbbbbbb3",
          header4: "bbbbbbbbbbbbbbbbbbbb4",
          header5: "bbbbbbbbbbbbbbbbbbbb5",
          header6: "bbbbbbbbbbbbbbbbbbbb6",
          header7: "bbbbbbbbbbbbbbbbbbbb7",
          header8: "bbbbbbbbbbbbbbbbbbbb8",
          header9: "bbbbbbbbbbbbbbbbbbbb9",
          header10: "bbbbbbbbbbbbbbbbbbbb10",
        },
        {
          header1: "cccccccccccccccccccc1",
          header2: "cccccccccccccccccccc2",
          header3: "cccccccccccccccccccc3",
          header4: "cccccccccccccccccccc4",
          header5: "cccccccccccccccccccc5",
          header6: "cccccccccccccccccccc6",
          header7: "cccccccccccccccccccc7",
          header8: "cccccccccccccccccccc8",
          header9: "cccccccccccccccccccc9",
          header10: "cccccccccccccccccccc10",
        },
        {
          header1: "dddddddddddddddddddd1",
          header2: "dddddddddddddddddddd2",
          header3: "dddddddddddddddddddd3",
          header4: "dddddddddddddddddddd4",
          header5: "dddddddddddddddddddd5",
          header6: "dddddddddddddddddddd6",
          header7: "dddddddddddddddddddd7",
          header8: "dddddddddddddddddddd8",
          header9: "dddddddddddddddddddd9",
          header10: "ddddddddddddddd10",
        },
        {
          header1: "eeeeeeeeee1",
          header2: "eeeeeeeeee2",
          header3: "eeeeeeeeee3",
          header4: "eeeeeeeeee4",
          header5: "eeeeeeeeee5",
          header6: "eeeeeeeeee6",
          header7: "eeeeeeeeee7",
          header8: "eeeeeeeeee8",
          header9: "eeeeeeeeee9",
          header10: "eeeeeeeeee10",
        },
        {
          header1: "ffffffffff1",
          header2: "ffffffffff2",
          header3: "ffffffffff3",
          header4: "ffffffffff4",
          header5: "ffffffffff5",
          header6: "ffffffffff6",
          header7: "ffffffffff7",
          header8: "ffffffffff8",
          header9: "ffffffffff9",
          header10: "ffffffffff10",
        },
        {
          header1: "gggggggggg1",
          header2: "gggggggggg2",
          header3: "gggggggggg3",
          header4: "gggggggggg4",
          header5: "gggggggggg5",
          header6: "gggggggggg6",
          header7: "gggggggggg7",
          header8: "gggggggggg8",
          header9: "gggggggggg9",
          header10: "gggggggggg10",
        },
        {
          header1: "hhhhhhhhhh1",
          header2: "hhhhhhhhhh2",
          header3: "hhhhhhhhhh3",
          header4: "hhhhhhhhhh4",
          header5: "hhhhhhhhhh5",
          header6: "hhhhhhhhhh6",
          header7: "hhhhhhhhhh7",
          header8: "hhhhhhhhhh8",
          header9: "hhhhhhhhhh9",
          header10: "hhhhhhhhhh10",
        },
        {
          header1: "eeeeeeeeee1",
          header2: "eeeeeeeeee2",
          header3: "eeeeeeeeee3",
          header4: "eeeeeeeeee4",
          header5: "eeeeeeeeee5",
          header6: "eeeeeeeeee6",
          header7: "eeeeeeeeee7",
          header8: "eeeeeeeeee8",
          header9: "eeeeeeeeee9",
          header10: "eeeeeeeeee10",
        },
        {
          header1: "iiiiiiiiii1",
          header2: "iiiiiiiiii2",
          header3: "iiiiiiiiii3",
          header4: "iiiiiiiiii4",
          header5: "iiiiiiiiii5",
          header6: "iiiiiiiiii6",
          header7: "iiiiiiiiii7",
          header8: "iiiiiiiiii8",
          header9: "iiiiiiiiii9",
          header10: "iiiiiiiiii10",
        },{
          header1: "aaaaaaaaaaaaaaaaaaaa1",
          header2: "aaaaaaaaaaaaaaaaaaaa2",
          header3: "aaaaaaaaaaaaaaaaaaaa3",
          header4: "aaaaaaaaaaaaaaaaaaaa4",
          header5: "aaaaaaaaaaaaaaaaaaaa5",
          header6: "aaaaaaaaaaaaaaaaaaaa6",
          header7: "aaaaaaaaaaaaaaaaaaaa7",
          header8: "aaaaaaaaaaaaaaaaaaaa8",
          header9: "aaaaaaaaaaaaaaaaaaaa9",
          header10: "aaaaaaaaaaaaaaaaaaaa10",
        },
        {
          header1: "bbbbbbbbbbbbbbbbbbbb1",
          header2: "bbbbbbbbbbbbbbbbbbbb2",
          header3: "bbbbbbbbbbbbbbbbbbbb3",
          header4: "bbbbbbbbbbbbbbbbbbbb4",
          header5: "bbbbbbbbbbbbbbbbbbbb5",
          header6: "bbbbbbbbbbbbbbbbbbbb6",
          header7: "bbbbbbbbbbbbbbbbbbbb7",
          header8: "bbbbbbbbbbbbbbbbbbbb8",
          header9: "bbbbbbbbbbbbbbbbbbbb9",
          header10: "bbbbbbbbbbbbbbbbbbbb10",
        },
        {
          header1: "cccccccccccccccccccc1",
          header2: "cccccccccccccccccccc2",
          header3: "cccccccccccccccccccc3",
          header4: "cccccccccccccccccccc4",
          header5: "cccccccccccccccccccc5",
          header6: "cccccccccccccccccccc6",
          header7: "cccccccccccccccccccc7",
          header8: "cccccccccccccccccccc8",
          header9: "cccccccccccccccccccc9",
          header10: "cccccccccccccccccccc10",
        },
        {
          header1: "dddddddddddddddddddd1",
          header2: "dddddddddddddddddddd2",
          header3: "dddddddddddddddddddd3",
          header4: "dddddddddddddddddddd4",
          header5: "dddddddddddddddddddd5",
          header6: "dddddddddddddddddddd6",
          header7: "dddddddddddddddddddd7",
          header8: "dddddddddddddddddddd8",
          header9: "dddddddddddddddddddd9",
          header10: "ddddddddddddddd10",
        },
        {
          header1: "eeeeeeeeee1",
          header2: "eeeeeeeeee2",
          header3: "eeeeeeeeee3",
          header4: "eeeeeeeeee4",
          header5: "eeeeeeeeee5",
          header6: "eeeeeeeeee6",
          header7: "eeeeeeeeee7",
          header8: "eeeeeeeeee8",
          header9: "eeeeeeeeee9",
          header10: "eeeeeeeeee10",
        },
        {
          header1: "ffffffffff1",
          header2: "ffffffffff2",
          header3: "ffffffffff3",
          header4: "ffffffffff4",
          header5: "ffffffffff5",
          header6: "ffffffffff6",
          header7: "ffffffffff7",
          header8: "ffffffffff8",
          header9: "ffffffffff9",
          header10: "ffffffffff10",
        },
        {
          header1: "gggggggggg1",
          header2: "gggggggggg2",
          header3: "gggggggggg3",
          header4: "gggggggggg4",
          header5: "gggggggggg5",
          header6: "gggggggggg6",
          header7: "gggggggggg7",
          header8: "gggggggggg8",
          header9: "gggggggggg9",
          header10: "gggggggggg10",
        },
        {
          header1: "hhhhhhhhhh1",
          header2: "hhhhhhhhhh2",
          header3: "hhhhhhhhhh3",
          header4: "hhhhhhhhhh4",
          header5: "hhhhhhhhhh5",
          header6: "hhhhhhhhhh6",
          header7: "hhhhhhhhhh7",
          header8: "hhhhhhhhhh8",
          header9: "hhhhhhhhhh9",
          header10: "hhhhhhhhhh10",
        },
        {
          header1: "eeeeeeeeee1",
          header2: "eeeeeeeeee2",
          header3: "eeeeeeeeee3",
          header4: "eeeeeeeeee4",
          header5: "eeeeeeeeee5",
          header6: "eeeeeeeeee6",
          header7: "eeeeeeeeee7",
          header8: "eeeeeeeeee8",
          header9: "eeeeeeeeee9",
          header10: "eeeeeeeeee10",
        },
        {
          header1: "iiiiiiiiii1",
          header2: "iiiiiiiiii2",
          header3: "iiiiiiiiii3",
          header4: "iiiiiiiiii4",
          header5: "iiiiiiiiii5",
          header6: "iiiiiiiiii6",
          header7: "iiiiiiiiii7",
          header8: "iiiiiiiiii8",
          header9: "iiiiiiiiii9",
          header10: "iiiiiiiiii10",
        }
      ],
      totalElements: 40,
      currentPage: 0,
      fromPage: 1, // show fist item on 1 showed page
      limit: 5,
      query: null,
      sort: null,
      sortASC: null,
      toPage: 5, // show last item on 1 showed page
      totalPages: 8 // totalElements/limit
    };
  }

}
